services:
  # The Python Backend Web Service
  - type: web
    name: universal-searcher-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: MONGO_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false

  # The Frontend Static Site
  - type: static_site # <--- This is the corrected line
    name: universal-searcher-frontend
    publishDirectory: "."
